data_config:
  batch_size: 128
  splits:
    train: 0.8
    test: 0.2

model_config:
  model_name: GAT
  hidden_size: 64
  n_layers: 2
  dropout_p: 0.5
  lr: 0.0005
  epochs: 200
  weight_decay: 2e-6

  multi_label: false
  learn_edge_att: false
  extractor_dropout_p: 0.5

sampler_config:
  Nnum_k: 0.5
  Gnum_m: 3
  temperature: 1
  separate: false
  edge_split: false
  pred_coef: 0.3
  sampler_coef: 0.7
  counter_coef: 0.1
